### PR TITLE
Single Request Box

### LINKED ISSUE #32: Select Chromosome and Region In Single Request Box
Eg. `chr20: 90000-95000`

Currently the chromosome is specified at the command line, and the region need to be entered in the start and end boxes.

### PR DESCRIPTION
**Pull request by erictu**
Resolves #32

### CODE REVIEW

**Comment by fnothaft** [comment]
Jenkins, retest this please.

**Comment by fnothaft** [comment]
@erictu can you look at the build failure here?

**Comment by erictu** [comment]
The hadoop 1.0.4 configuration failed. `Required file not found: sbt-interface.jar` Should we just try building it again?

**Comment by fnothaft** [comment]
Jenkins, retest this please.

**Comment by fnothaft** [comment]
Closed by https://github.com/bigdatagenomics/mango/commit/7858c5ab78b8e6886c0313341b87747c5dd2d7f5.

**Pull request closed without merging**
