### PR TITLE
frontend changes transfered to .scss and compiled .css with koala

### PR DESCRIPTION
**Pull request by dorislee0309**

### CODE REVIEW

**Comment by akmorrow13** [comment]
Jenkins, test this please.

**Comment by akmorrow13** [comment]
@erictu I don't think I can initiate Jenkins, please test

**Comment by fnothaft** [comment]
@akmorrow13 
> @erictu I don't think I can initiate Jenkins, please test

Just fixed this! You should be able to now.

**Comment by fnothaft** [comment]
Jenkins, test this please.

**Pull request merged**
