### PR TITLE
Removed ReferenceMapping, Clean up VizReads

### PR DESCRIPTION
**Pull request by erictu**

### CODE REVIEW

**Comment by fnothaft** [comment]
This deletes the current test suites (which were just for `ReferenceMapping`), correct? Jenkins is complaining about not having xml files with the test results.

**Comment by erictu** [comment]
Yes that's correct.

**Comment by fnothaft** [comment]
Cool, let me persuade @AmplabJenkins to understand.

**Comment by fnothaft** [comment]
Jenkins, retest this please.

**Comment by fnothaft** [comment]
Merged! Thanks @erictu!

**Pull request merged**
