### PR TITLE
Asynchronous Backend Changes

### PR DESCRIPTION
**Pull request by Georgehe4**
Clean up backend calls and fix asynchronous loading issues.

Note: Issue with timer still awaiting fix.

### CODE REVIEW

**Comment by akmorrow13** [comment]
Is there anyway to completely remove the globalViewRegion in the backend? I only say this because to support multiple clients this may be an issue.

**Comment by Georgehe4** [comment]
Removing globalViewRegion is possible but would require the client to track local sessions. We'd have to switch to client-side cookies to track session information - should address this in person.

**Comment by akmorrow13** [comment]
Got it. That sounds like another project we can merge this in and talk later

**Comment by akmorrow13** [comment]
Jenkins, test this please.

**Comment by erictu** [comment]
Jenkins, test this please.

**Pull request merged**
