### PR TITLE
Update README.md - actual version of Hadoop

### PR DESCRIPTION
**Pull request by LeonisX**

### CODE REVIEW

**Comment by LeonisX** [comment]
I want to explain these changes.
When read code in IntelliJ Idea, IDE show too many warnings and show where need to correct code. Warnings too much, is is hard to navigate.

I removed:
1. Unused imports
2. Unnecessary semicolons
2. Unnecessary parentheses

Added parentheses to methods, when need

Don't touched unnecessary braces in match/case (think, this is preferred style)

Now code have 22 warnings

**Comment by akmorrow13** [comment]
Jenkins, test this please.

**Comment by LeonisX** [comment]
I beg your pardon, I did not check the assembly. IDEA also sometimes make mistakes. Returned missing import org.json4s._

**Comment by akmorrow13** [comment]
No worries, please make the update, and run 'mvn package' to make sure all compiles

**Comment by LeonisX** [comment]
Now all OK, all tests passed :)

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] mango: an ADAM-based genomics visualization toolkit  SUCCESS [  2.584 s]
[INFO] mango-core: an ADAM-based genomics visualization toolkit SUCCESS [01:00 min]
[INFO] mango-cli: an ADAM-based genomics visualization toolkit SUCCESS [ 12.876 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:16 min
[INFO] Finished at: 2016-03-17T12:35:20+02:00
[INFO] Final Memory: 39M/868M
[INFO] ------------------------------------------------------------------------

**Comment by akmorrow13** [comment]
Jenkins, test this please.

**Comment by akmorrow13** [comment]
Thanks, Leonis. Just an update on the state of Mango: we are currently in rapid development and hope to have a smooth version up and ready by May. We have still many features to implement such as the main log in page and scalable visualizations. You're contribution is welcome! Otherwise, I can update you when version 1 is up and running publicly.

**Comment by LeonisX** [comment]
OK, good luck ;)

**Pull request merged**
