### PR TITLE
[MANGO-546] Update ADAM dependency version to 0.30.0

### LINKED ISSUE #546: Update ADAM dependency version to 0.30.0
Will also require bumping `bdg-formats` and `bdg-convert` versions.

### PR DESCRIPTION
**Pull request by heuermh**
Fixes #546

Work in progress, will require bumping ADAM python library version when it has been released.

### CODE REVIEW

**Comment by akmorrow13** [comment]
Looks like we need to modify the python code with the new API:

`py4j.protocol.Py4JError: org.bdgenomics.mango.converters.GA4GHutil.alignmentRecordDatasetToJSON does not exist in the JVM`

**Comment by heuermh** [comment]
> Looks like we need to modify the python code with the new API...

Yep, I have not made the 0.30.0 python release to PyPI yet

**Comment by akmorrow13** [comment]
@heuermh do you want me to make the release?

**Comment by heuermh** [comment]
Yeah, I feel like I should fix this issue at some point (by splitting Python ADAM to a separate repo?) but haven't gotten around to it yet.

The release branch is
https://github.com/bigdatagenomics/adam/tree/maint_spark2_2.11-0.30.0

Thanks!

**Comment by akmorrow13** [comment]
Closing in favor of https://github.com/bigdatagenomics/mango/pull/548

**Comment by heuermh** [comment]
Thank you, @akmorrow13

**Pull request closed without merging**
