### PR TITLE
added http endpoint for coverage

### PR DESCRIPTION
**Pull request by akmorrow13**

### CODE REVIEW

**Comment by david4096** [comment]
Could you describe the usage of this? I've been thinking about a similar thing for GA4GH genomics API.

**Comment by akmorrow13** [comment]
That would be a great thing to have in the GA4GH API, @david4096 ! Currently pileup.js (a frontend browser) calculates coverage from alignments in the frontend. This inhibits coverage from being displayed at large regions. We compute coverage in the backend based on the size of the region requested. I am returning a list of position counts (position, count) because at large regions we are not returning all of the data, and thus need the position. Does that make sense?

**Comment by david4096** [comment]
I was thinking that search endpoints return a `count` of total results. This would allow you to specify queries with a very small data dump using the same endpoints (set `page_size=1` but ask for a huge region). Instead of having a separate endpoint you could calculate different coverage binnings by modifying the start and end-points of the query.

**Comment by akmorrow13** [comment]
Jenkins, retest this please.

**Pull request merged**
